avatar = "https://ae01.alicdn.com/kf/HTB1DdGHXizxK1RjSspj763S.pXax.png"
desc = "Technology craftsman ( Developer, Designer, Blogger )"
email = "WincerChan@gmail.com"

[name]
base = "Wincer"
note = "/ˈwɪnsə(r)/"

[[links]]
name = "blog"
url = "https://blog.itswincer.com"
color = "#FF9A00"
title = "Wincer's Blog" 

[[links]]
name = "github"
url = "https://github.com/WincerChan"
color = "#24292F"
title = '@WincerChan'

[[links]]
name = "telegram"
url ="https://t.me/Tivsae"
title = '@Tivsae'
color = "#22A6DC"


[[Portfolio]]
name = "TalkGPT"
url = "https://github.com/WincerChan/TalkGPT"
cover = "https://pic.imgdb.cn/item/641e7af1a682492fcc3734c7.jpg"
desc = "CLI tool for voice conversation with ChatGPT"

[[Portfolio]]
name = "Meme-Generator"
url = "https://github.com/WincerChan/Meme-Generator"
cover = "https://pic.imgdb.cn/item/641e7c52a682492fcc3a385b.jpg"
desc = "Meme Generator for pure javascript"

[[Portfolio]]
name = "Mirror"
url = "https://github.com/WincerChan/Mirror"
cover = "https://pic.imgdb.cn/item/641e7cb0a682492fcc3abb28.jpg"
desc = "Golang reverse proxy tool"

[[Portfolio]]
name = "Cirrus"
url = "https://github.com/WincerChan/Cirrus"
cover = "https://help-ol.bj.bcebos.com/cd44890e52c79416fc9e34b8532c4597.jpg"
desc = "Minimalist Hugo blog theme"