avatar = "https://ae01.alicdn.com/kf/HTB1DdGHXizxK1RjSspj763S.pXax.png"
desc = "Technology craftsman ( Developer, Designer, Blogger )"
email = "WincerChan@gmail.com"

[name]
base = "Wincer"
note = "/ˈwɪnsə(r)/"

[[links]]
name = "github"
url = "https://github.com/WincerChan"
color = "#24292F"
title = '@WincerChan'

[[links]]
name = "telegram"
url ="https://t.me/Tivsae"
title = '@Tivsae'
color = "#22A6DC"

[[links]]
name = "blog"
url = "https://blog.itswincer.com"
color = "#FF9A00"
title = "Wincer's Blog" 


[[Portfolio]]
name = "TalkGPT"
url = "https://github.com/WincerChan/TalkGPT"
cover = "https://images.unsplash.com/photo-1679379121012-d75e987c60ff"
desc = "CLI tool for voice conversation with ChatGPT"

[[Portfolio]]
name = "Meme-Generator"
url = "https://github.com/WincerChan/Meme-Generator"
cover = "https://images.unsplash.com/photo-1679471491129-9e2f3ea6ec3f"
desc = "Meme Generator for pure javascript"